#!/usr/bin/env python


import os

programName = 'summertime'

rootpath = '../../'

envGlobal = Environment(toolpath=[os.path.join(rootpath, 'scons-build-tools/site_tools')],
                        buildroot=[rootpath + 'build/'],
                        tools=['utils_buildformat', 'utils_buildsize'],
                        OS='freertos',
                        DEVICE_SIZE={
                          'name' : 'NRF51822',
                          'flash': 128*1024,
                          'ram'  :  16*1024
                        },
                        BASEPATH=os.path.abspath('.'),
                        ENV=os.environ)
#Help(vars.GenerateHelpText(envGlobal))

envGlobal.Tool('compiler_arm_none_eabi_gcc')
envGlobal.AppendUnique(CCFLAGS_optimize=['-fno-strict-aliasing', '-fno-builtin', '--short-enums', '-O3', '-g3'])
envGlobal.AppendUnique(CCFLAGS_target=['-mcpu=cortex-m0', '-mfloat-abi=soft', '-mthumb', '-mabi=aapcs'])
envGlobal.Append(LINK_FLAGS_other=['--specs=nano.specs', '-lc', '-lnosys'])

buildfolder = os.path.join(rootpath, 'build')
envGlobal.Tool('settings_buildpath')
envGlobal['BUILDPATH'] = os.path.abspath(buildfolder)
envGlobal['LIBINSTALLPATH'] = os.path.join(envGlobal['BUILDPATH'], 'lib')
envGlobal.Append(LIBPATH=envGlobal['LIBINSTALLPATH'])

envGlobal.RemoveFromList('CCFLAGS_other', ['-fshort-wchar', '-finline-limit=10000'])

envGlobal.Append(CPPPATH=[os.path.abspath('./config')])
envGlobal['LD_FILE'] = os.path.join(os.path.abspath('./config'), 'summertime_gcc_nrf51.ld')
envGlobal.SConscript(os.path.join(rootpath, 'SConscript.sdk'), exports='envGlobal')
env = envGlobal.Clone()

env.AppendUnique(LIBS=[
    'nrf_sdk',
])

files = env.Glob('*.c')

program = env.Program(programName, files)
#envGlobal.Size(0)
envGlobal.Alias('build', program)
envGlobal.Alias('build', env.Size(program))
envGlobal.Default('build')
